disabled_rules:
 
  - anyobject_protocol
  - array_init 
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment 
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type 
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - dynamic_inline
  - empty_count 
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  # - file_header
  # - file_name
  - file_types_order
  - first_where
  - force_unwrapping
  - force_cast
  - warning_threshold
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - indentation_width
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - large_tuple
  - last_where
  - legacy_multiple
  - legacy_random
  # - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets  
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace 
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing 
  - redundant_type_annotation
  - required_enum_case
  - shorthand_operator 
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  # - todo
  - toggle_bool
  - trailing_closure
  # - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

excluded:
  - Pods
  - vendor

line_length:
  warning: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

type_body_length: 500

file_length: 500

type_name:
  min_length: 2
  max_length: 40
  allowed_symbols: ["_"]

identifier_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - i
    - j
    - x
    - y
    - z
    - id
    - URL
    - GlobalAPIKey
    - r
    - g
    - b
  allowed_symbols: ["_"]

cyclomatic_complexity:
  ignores_case_statements: true
  error: 50

indentation_width:
  indentation_width: 2
  include_comments: false

function_body_length: 100

large_tuple:
  error: 4

conditional_returns_on_newline:
  if_only: true  

attributes:
  always_on_same_line: ["@objc", "@discardableResult", "@nonobjc"]
  always_on_line_above: ["@available"]

closure_body_length: 40


